version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: speck_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: speck
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: speck_backend
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"

volumes:
  pgdata:
